name: Deploy WordPress Theme

on:
  push:
    branches:
      - main  # Or your primary branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Print debug info about secrets (without revealing them)
      - name: Check secrets
        run: |
          if [ -n "${{ secrets.SSH_HOST }}" ]; then echo "SSH_HOST is set"; else echo "SSH_HOST is NOT set"; fi
          if [ -n "${{ secrets.SSH_USER }}" ]; then echo "SSH_USER is set"; else echo "SSH_USER is NOT set"; fi
          if [ -n "${{ secrets.SSH_PASSWORD }}" ]; then echo "SSH_PASSWORD is set"; else echo "SSH_PASSWORD is NOT set"; fi

      # Use pre-installed sshpass on GitHub runners
      - name: Test SSH connection (minimal)
        run: |
          echo "Testing connection to host: ${{ secrets.SSH_HOST }}"
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" echo "Connection successful"

      # Deployment step (if connection successful)
      - name: Deploy to WordPress themes directory
        run: |
          echo "Deploying to ${{ secrets.SSH_HOST }}..."
          sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            --exclude=".git/" \
            --exclude=".github/" \
            --exclude="node_modules/" \
            --exclude=".gitignore" \
            ./ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/portfolio.lucidica.co.uk/public_html/wp-content/themes/lucidica-portfolio/"