name: Deploy WordPress Theme

on:
  push:
    branches:
      - main  # Or your primary branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Print the exact values we're using (but mask sensitive parts)
      - name: Debug connection string
        run: |
          echo "User: ${{ secrets.SSH_USER || 'NOT SET' }}"
          echo "Host: ${{ secrets.SSH_HOST || 'NOT SET' }}"
          echo "Connection string: ${{ secrets.SSH_USER || 'user' }}@${{ secrets.SSH_HOST || 'host' }}:/path"
          echo "Password is set: ${{ secrets.SSH_PASSWORD != '' }}"

      - name: Deploy to WordPress themes directory
        run: |
          # Check if required secrets are set
          if [ -z "${{ secrets.SSH_USER }}" ]; then
            echo "Error: SSH_USER secret is not set"
            exit 1
          fi
          
          if [ -z "${{ secrets.SSH_HOST }}" ]; then
            echo "Error: SSH_HOST secret is not set"
            exit 1
          fi
          
          if [ -z "${{ secrets.SSH_PASSWORD }}" ]; then
            echo "Error: SSH_PASSWORD secret is not set"
            exit 1
          fi
          
          echo "Deploying to ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/portfolio.lucidica.co.uk/public_html/wp-content/themes/lucidica-portfolio/"
          
          sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            --exclude=".git/" \
            --exclude=".github/" \
            --exclude="node_modules/" \
            --exclude=".gitignore" \
            ./ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/portfolio.lucidica.co.uk/public_html/wp-content/themes/lucidica-portfolio/"