name: Deploy WordPress Theme

on:
  push:
    branches:
      - main  # Or your primary branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Debug step to verify secrets
      - name: Debug secret availability
        run: |
          if [ -n "${{ secrets.SSH_HOST }}" ]; then 
            echo "SSH_HOST is set"
          else 
            echo "SSH_HOST is NOT set" 
          fi
          if [ -n "${{ secrets.SSH_USER }}" ]; then 
            echo "SSH_USER is set"
          else 
            echo "SSH_USER is NOT set" 
          fi
          if [ -n "${{ secrets.SSH_PASSWORD }}" ]; then 
            echo "SSH_PASSWORD is set (value hidden)"
          else 
            echo "SSH_PASSWORD is NOT set" 
          fi

      # Install sshpass with sudo
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      # Test SSH connection with proper syntax
      - name: Test SSH connection
        run: |
          echo "Attempting to connect to ${{ secrets.SSH_HOST }}..."
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Connection successful"

      # Deploy with correct syntax
      - name: Deploy to WordPress themes directory
        run: |
          echo "Starting deployment to ${{ secrets.SSH_HOST }}..."
          sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            --exclude=".git/" \
            --exclude=".github/" \
            --exclude="node_modules/" \
            --exclude=".gitignore" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/subdomain.yourdomain.com/public_html/wp-content/themes/your-theme-name/
          echo "Deployment completed"
      
      # Optional: Clear WordPress cache
      - name: Clear cache
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "wp cache flush --path=/var/www/subdomain.yourdomain.com/public_html" || echo "Cache flush failed, but continuing"